### ISSUE TITLE
Bug when i clic to add pbr node on blender 2.8

### ISSUE THREAD

**Issue by sramauge** [RaghavVenkat/pbrify#1]
![Capture2](https://user-images.githubusercontent.com/42722419/61595803-1b525680-abfc-11e9-9c1b-c0e7f68b581e.PNG)

**Comment by sramauge** [comment]
After download and install the last version, i'have this when i want activate it 

![Capture3](https://user-images.githubusercontent.com/42722419/61595932-82243f80-abfd-11e9-9d33-80b66293679c.PNG)

**Comment by RaghavVenkat** [comment]
> After download and install the last version, i'have this when i want activate it
> 
> ![Capture3](https://user-images.githubusercontent.com/42722419/61595932-82243f80-abfd-11e9-9d33-80b66293679c.PNG)

@sramauge  Download the single pbrify.py python file. That should fix this.

**Comment by RaghavVenkat** [comment]
I think you are using Blender 2.80 Candidate release. Currently, this is compatible with 2.7x and 2.8 Beta versions. I'll let you know once the addon is updated for 2.80 candidate and stable versions.

**Comment by RaghavVenkat** [comment]
**I've updated the addon for Blender 2.7x, 2.8x beta + RC version and also tested this on blender 2.79, blender 2.80 Beta, and also on the latest RC version. It seemed to have worked perfectly**. Thanks for letting me know about this issue! @sramauge You can now download the latest file from my [repo] (https://github.com/RaghavVenkat/pbrify/blob/master/release/pbrify.py) or from here [https://gumroad.com/iraghavvenkat#lROfO](https://gumroad.com/iraghavvenkat#lROfO) 

_Happy Blending!_
